"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { motion, useScroll, useTransform } from "framer-motion";
import "./globals.css";
import Footer from "@/components/temp/footer";
import Navbar from "@/components/temp/navbar";
import { usePathname } from "next/navigation";
import { useEffect } from "react";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// const { scrollYProgress } = useScroll();
	// const pathname = usePathname();
	// const navOpacity =
	// 	pathname === "/test0"
	// 		? useTransform(scrollYProgress, [0.7, 1], [0, 1])
	// 		: useTransform(scrollYProgress, [1], [1]);

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
			>
				<div className="flex flex-col min-h-screen">
					<Navbar />
					<div className="flex-1">{children}</div>
					<Footer />
				</div>
				{/* <motion.div
					style={{ opacity: navOpacity }}
					className="fixed top-[10px] left-1/2 -translate-x-1/2 z-50"
				>
					<Navbar />
				</motion.div> */}
				{/* {children} */}
				{/* <Footer /> */}
			</body>
		</html>
	);
}
